### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [posktomten/hashsum#1]
Please provide the AppImage for download on https://github.com/posktomten/hashsum/releases/tag/2.3.0.a, not just the source code. Thanks.

**Comment by probonopd** [comment]
Hi, I don't see an AppImage link on https://github.com/posktomten/hashsum/releases...

**Comment by probonopd** [comment]
Getting

```
libc.so.6: version `GLIBC_2.25' not found (required by /run/firejail/appimage/.appimage-7057/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for the solution. Thanks, keep up your great work!

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/366468012#L599

**Comment by probonopd** [comment]
Or you could use linuxdeployqt with a hosted service like Travis CI. Here is an example:
https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci

**Comment by posktomten** [comment]
Hm. Strange I tested on Lubuntu 14.04 live CD
"Hashsum-x86_64_old_static.AppImage
Compiled on Lubuntu 14.04, Glibc 2.19, GCC 4.8.4. Uses Qt 10.1 that is static linked.
Tested on Lubuntu 14.04, for older Linux distros"

The one compiled on Lubuntu 18.04, Glibc 2.27, Qt 11.1, GCC 7.3.0 only works on newer Linux. (Tested on Lubuntu 18.04 live CD) But the other works for me.

**Comment by probonopd** [comment]
So there is no real advantage of having two (which is conufising) if `Hashsum-x86_64_old_static.AppImage` works on old _and_ new distributions...
